name: cabinet
description: cabinet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  dio: ^3.0.9
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  flutter_easyrefresh: ^1.2.7
  event_bus: ^1.1.1
  path_provider: ^0.5.0+1
  shared_preferences: ^0.5.6
  webview_flutter: ^0.3.19+9
  flutter_webview_plugin: ^0.3.11
  qrscan: ^0.2.17
  provider: ^5.0.0
  fluttertoast: ^4.0.0
  url_launcher: ^5.4.2
  date_format: ^1.0.8
  permission_handler: ^5.0.1+1
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^5.0.0
#  scan: 0.0.7
#  images_picker: 0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon_register_confirm.png
    - assets/img/icon_login_bg.png
    - assets/img/icon_login_op_bg.png
    - assets/img/icon_device_default.png
    - assets/img/icon_device_locked.png
    - assets/img/icon_scan_qr.png
    - assets/img/icon_user_guide.png
    - assets/img/iocn_me_top.png
    - assets/img/icon_device_empty.png
    - assets/img/icon_scan_qr_device_bg.png
    - assets/img/icon_scan_qr_device.png
    - assets/img/icon_me_unselecte.png
    - assets/img/icon_device_select.png
    - assets/img/icon_device_unselecte.png
    - assets/img/icon_me_select.png
    - assets/img/icon_lock_op.png
    - assets/img/icon_splash.png
    - assets/img/icon_splash_bg.png
    - assets/img/ic_launcher.png
    - assets/img/icon_avater_defalut.png
    - assets/img/icon_me_select.png
    - assets/img/icon_device_unselecte.png
    - assets/img/icon_update.png
    - assets/img/icon_service.png
    - assets/img/icon_introduce.png
    - assets/img/icon_guizi_info.png
    - assets/img/icon_help.png

flutter_intl:
  enabled: true
